package edu.jhu.fcriscu1.vep.database.model;

public class VepJsonCache {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onco_json_cache.CACHE_KEY
     *
     * @mbggenerated Sun Apr 12 16:06:59 EDT 2015
     */
    private String CACHE_KEY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column onco_json_cache.RAW_JSON
     *
     * @mbggenerated Sun Apr 12 16:06:59 EDT 2015
     */
    private String RAW_JSON;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onco_json_cache.CACHE_KEY
     *
     * @return the value of onco_json_cache.CACHE_KEY
     *
     * @mbggenerated Sun Apr 12 16:06:59 EDT 2015
     */
    public String getCACHE_KEY() {
        return CACHE_KEY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onco_json_cache.CACHE_KEY
     *
     * @param CACHE_KEY the value for onco_json_cache.CACHE_KEY
     *
     * @mbggenerated Sun Apr 12 16:06:59 EDT 2015
     */
    public void setCACHE_KEY(String CACHE_KEY) {
        this.CACHE_KEY = CACHE_KEY == null ? null : CACHE_KEY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column onco_json_cache.RAW_JSON
     *
     * @return the value of onco_json_cache.RAW_JSON
     *
     * @mbggenerated Sun Apr 12 16:06:59 EDT 2015
     */
    public String getRAW_JSON() {

        return RAW_JSON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column onco_json_cache.RAW_JSON
     *
     * @param RAW_JSON the value for onco_json_cache.RAW_JSON
     *
     * @mbggenerated Sun Apr 12 16:06:59 EDT 2015
     */
    public void setRAW_JSON(String RAW_JSON) {
        this.RAW_JSON = RAW_JSON == null ? null : RAW_JSON.trim();
    }
}