package edu.jhu.fcriscu1.vep.database.dao;

import edu.jhu.fcriscu1.vep.database.model.VepJsonCache;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import edu.jhu.fcriscu1.vep.database.model.VepJsonCacheExample;

public interface VepJsonCacheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onco_json_cache
     *
     * @mbggenerated Sun Apr 12 16:06:59 EDT 2015
     */
    int countByExample(VepJsonCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onco_json_cache
     *
     * @mbggenerated Sun Apr 12 16:06:59 EDT 2015
     */
    int deleteByExample(VepJsonCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onco_json_cache
     *
     * @mbggenerated Sun Apr 12 16:06:59 EDT 2015
     */
    int insert(VepJsonCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onco_json_cache
     *
     * @mbggenerated Sun Apr 12 16:06:59 EDT 2015
     */
    int insertSelective(VepJsonCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onco_json_cache
     *
     * @mbggenerated Sun Apr 12 16:06:59 EDT 2015
     */
    List<VepJsonCache> selectByExampleWithBLOBs(VepJsonCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onco_json_cache
     *
     * @mbggenerated Sun Apr 12 16:06:59 EDT 2015
     */
    List<VepJsonCache> selectByExample(VepJsonCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onco_json_cache
     *
     * @mbggenerated Sun Apr 12 16:06:59 EDT 2015
     */
    int updateByExampleSelective(@Param("record") VepJsonCache record, @Param("example") VepJsonCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onco_json_cache
     *
     * @mbggenerated Sun Apr 12 16:06:59 EDT 2015
     */
    int updateByExampleWithBLOBs(@Param("record") VepJsonCache record, @Param("example") VepJsonCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onco_json_cache
     *
     * @mbggenerated Sun Apr 12 16:06:59 EDT 2015
     */
    int updateByExample(@Param("record") VepJsonCache record, @Param("example") VepJsonCacheExample example);
}